version: "3.7"

services:

  # #############################################################################################
  # ###                                        POSTGRES                                       ###
  # #############################################################################################
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432

  # #############################################################################################
  # ###                                        SONARQUBE                                      ###
  # #############################################################################################      
  sonarqube:
    image: sonarqube:lts
    ports:
      - 9000:9000
 
  # #############################################################################################
  # ###                                        KEYCLOAK                                       ###
  # #############################################################################################
  keycloak:
    image: quay.io/keycloak/keycloak
    environment:
      DB_VENDOR: H2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /tmp/realm-export.json
      KEYCLOAK_FRONTEND_URL: http://localhost:8081/auth
    volumes:
      - ./infrastructure/keycloak/realm-export.json:/tmp/realm-export.json
    ports:
      - 8081:8080

  # #############################################################################################
  # ###                                        KEYCLOAK Config                                ###
  # #############################################################################################
  keycloak-config:
    command: sh -c "dockerize -wait http://keycloak:8080 -timeout 300s /tmp/createuser.sh"     