server:
  servlet:
    context-path: /spring-demo
  port: 9002

spring:
  application:
    name: demo
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: ${DB_DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        default_schema: demo
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        validator:
          apply_to_ddl: false
        jdbc: 
          time_zone: UTC

  flyway:
    url: jdbc:postgresql://${DB_HOST:localhost:5432/demo}
    schemas: demo
    user: ${DB_USER:postgres}
    password: ${DB_PASS:password}
    baseline-on-migrate: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost:5432/demo}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:password}
   